### ISSUE TITLE
Make existing redirects from www.mozilla.com to www.mozilla.org 301s

### ISSUE THREAD

**Issue by pmac** [mozilla-it/refractr#60]
@rraue has brought to our attention that Google (and possibly others) are still indexing URLs at www.mozilla.com even though they are all redirects. The theory is that the redirects that are indexed are 302 (temporary) instead of 301 (permanent) responses. We'd like to convert all 302 redirects from www.mozilla.com (and possibly also mozilla.com apex domain) to 301s.

@rraue please add any supporting info you think is relevant.

**Comment by rraue** [comment]
Did you already change anything? I crawled all urls Google still has in its index and pinged all of them for status and now all urls are 301, that was not the case yesterday.

Here is the list of urls I see still being indexed: https://docs.google.com/spreadsheets/d/1CBz4czunUE1P-PTvCbcZ5n-YF4aqNCPVqacmv-gCgYA/edit?usp=sharing

**Comment by pmac** [comment]
We can see if @sidler-mozilla can get us the current config for the redirector to see if maybe the 302s are only in certain cases with certain request headers. I haven't tested all of the URLs in your doc, but I can if you'd like another test.

**Comment by sidler-mozilla** [comment]
If this is still an issue, please help me identify the source of the issue with a PR please. [prod-refractr.yml](https://github.com/mozilla-it/refractr/blob/main/prod-refractr.yml) has all of the redirects. If status is not specified, it defaults to `301`. /cc @pmac @rraue

**Comment by sidler-mozilla** [comment]
https://github.com/mozilla-it/refractr/blob/main/prod-refractr.yml#L326-L366 could this be the source of those 302s?

**Comment by caugner** [comment]
@pmac Meanwhile, https://www.mozilla.com/ seems to redirect with a HTTP 301 to https://www.mozilla.org/firefox, so I guess this can be closed?

```
% curl -I https://www.mozilla.com/
HTTP/2 301 
date: Tue, 25 Jun 2024 09:00:29 GMT
content-type: text/html
content-length: 162
location: https://www.mozilla.org/firefox
strict-transport-security: max-age=60; includeSubDomains
x-frame-options: SAMEORIGIN
content-security-policy: frame-ancestors 'none'
```

**Comment by ahoneiser** [comment]
I think we can close this :ok_hand: if you want to have another look at this, @pmac & @caugner, please let me know :slightly_smiling_face:
